name: Build wasm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install emsdk and build wasm
        run: cd ./script/wasm && sudo bash ./build-wasm.bash
